import { PrismaClient } from '@prisma/client';
import { S3Client, PutObjectCommand, HeadBucketCommand, CreateBucketCommand } from '@aws-sdk/client-s3';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

// ---------------------------------------------------------------------------
// Real Gaussian Splat PLY generator
//
// Creates a proper 3DGS PLY file with xyz, SH coefficients (f_dc_0..2,
// f_rest_0..44), opacity, scale_0..2, rot_0..3 per the standard format.
// Generates an interior room scene: floor, walls, furniture-like shapes.
// ---------------------------------------------------------------------------

function generateGaussianSplatPLY(pointCount: number): Buffer {
  const header = `ply
format binary_little_endian 1.0
comment Generated by OpenGaussian Demo Creator
element vertex ${pointCount}
property float x
property float y
property float z
property float nx
property float ny
property float nz
property float f_dc_0
property float f_dc_1
property float f_dc_2
property float f_rest_0
property float f_rest_1
property float f_rest_2
property float f_rest_3
property float f_rest_4
property float f_rest_5
property float f_rest_6
property float f_rest_7
property float f_rest_8
property float f_rest_9
property float f_rest_10
property float f_rest_11
property float f_rest_12
property float f_rest_13
property float f_rest_14
property float f_rest_15
property float f_rest_16
property float f_rest_17
property float f_rest_18
property float f_rest_19
property float f_rest_20
property float f_rest_21
property float f_rest_22
property float f_rest_23
property float f_rest_24
property float f_rest_25
property float f_rest_26
property float f_rest_27
property float f_rest_28
property float f_rest_29
property float f_rest_30
property float f_rest_31
property float f_rest_32
property float f_rest_33
property float f_rest_34
property float f_rest_35
property float f_rest_36
property float f_rest_37
property float f_rest_38
property float f_rest_39
property float f_rest_40
property float f_rest_41
property float f_rest_42
property float f_rest_43
property float f_rest_44
property float opacity
property float scale_0
property float scale_1
property float scale_2
property float rot_0
property float rot_1
property float rot_2
property float rot_3
end_header
`;

  // Sigmoid / inverse sigmoid for opacity encoding
  const invSigmoid = (v: number): number => {
    const clamped = Math.max(0.001, Math.min(0.999, v));
    return Math.log(clamped / (1 - clamped));
  };

  // Standard 3DGS: color = SH_C0 * f_dc + 0.5
  // So to encode a desired color c: f_dc = (c - 0.5) / SH_C0
  const SH_C0 = 0.28209479177387814;
  const colorToSH = (c: number): number => (c - 0.5) / SH_C0;

  // Room bounds (modern living room)
  const roomW = 4.0;   // half-width  (x)
  const roomD = 3.5;   // half-depth  (z)
  const roomH = 2.7;   // ceiling height

  const stride = 62 * 4; // 62 floats per vertex
  const buf = Buffer.alloc(header.length + pointCount * stride);
  buf.write(header, 0, 'ascii');

  let offset = header.length;

  // Simple random that avoids 0 exactly for inverse sigmoid
  const rand = (lo: number, hi: number): number =>
    lo + Math.random() * (hi - lo);

  const clamp = (v: number, lo: number, hi: number): number =>
    Math.max(lo, Math.min(hi, v));

  // Object types for surface coloring
  type SurfaceType = 'floor' | 'wall' | 'ceiling' | 'sofa' | 'table' | 'tv' | 'rug' | 'plant' | 'lamp';

  interface SurfaceColor { r: number; g: number; b: number; roughness: number; }
  const surfaceColors: Record<SurfaceType, SurfaceColor> = {
    floor:   { r: 0.45, g: 0.35, b: 0.25, roughness: 0.7 },
    wall:    { r: 0.92, g: 0.90, b: 0.86, roughness: 0.85 },
    ceiling: { r: 0.96, g: 0.95, b: 0.92, roughness: 0.9 },
    sofa:    { r: 0.40, g: 0.40, b: 0.42, roughness: 0.6 },
    table:   { r: 0.35, g: 0.22, b: 0.12, roughness: 0.5 },
    tv:      { r: 0.08, g: 0.08, b: 0.10, roughness: 0.2 },
    rug:     { r: 0.75, g: 0.68, b: 0.60, roughness: 0.75 },
    plant:   { r: 0.15, g: 0.55, b: 0.20, roughness: 0.6 },
    lamp:    { r: 0.95, g: 0.90, b: 0.70, roughness: 0.3 },
  };

  // Poor man's SDF: decide surface type based on position
  function classifyPoint(x: number, y: number, z: number): SurfaceType {
    const floorY = -roomH * 0.45;
    const eps = 0.08;

    // Floor
    if (y < floorY + eps) return 'floor';
    // Ceiling
    if (y > roomH * 0.45 - eps) return 'ceiling';

    // Sofa at left-back
    const sofaX = -1.5, sofaZ = 1.0, sofaW = 1.6, sofaD = 0.8, sofaH = 0.7;
    if (Math.abs(x - sofaX) < sofaW + 0.15 && Math.abs(z - sofaZ) < sofaD + 0.15 && y < sofaH + floorY + 0.1) {
      return 'sofa';
    }

    // Coffee table center
    const tableX = 0, tableZ = 0.2, tableW2 = 0.7, tableD2 = 0.5, tableH2 = 0.45;
    if (Math.abs(x - tableX) < tableW2 + 0.1 && Math.abs(z - tableZ) < tableD2 + 0.1 && y < tableH2 + floorY + 0.08) {
      return 'table';
    }

    // TV unit front center
    const tvX = 0, tvZ = -roomD + 0.3, tvW3 = 1.8, tvH3 = 0.9, tvBaseY = floorY + 0.4;
    if (Math.abs(x - tvX) < tvW3 + 0.1 && Math.abs(z - tvZ) < 0.2 && y > tvBaseY - 0.05 && y < tvBaseY + tvH3 + 0.1) {
      return y < tvBaseY + tvH3 * 0.6 ? 'tv' : 'wall';
    }

    // Rug
    if (Math.abs(x) < 2.0 && Math.abs(z) < 1.5 && y < floorY + 0.02) return 'rug';

    // Plant pot right corner
    if (Math.sqrt((x - 2.2) ** 2 + (z - 2.2) ** 2) < 0.35 && y < floorY + 1.0) return 'plant';

    // Lamp right-back
    if (Math.sqrt((x - 2.0) ** 2 + (z - 1.5) ** 2) < 0.25 && y < floorY + 1.6) return 'lamp';

    // Wall detection
    const dx = roomW - Math.abs(x);
    const dz = roomD - Math.abs(z);
    const minDistToWall = Math.min(dx, dz);
    if (minDistToWall < 0.2) return 'wall';

    return 'wall';
  }

  for (let i = 0; i < pointCount; i++) {
    // Sample points from room surfaces and object volumes
    let x: number, y: number, z: number;
    let surface: SurfaceType;

    const choice = Math.random();

    if (choice < 0.15) {
      // Floor points
      x = rand(-roomW, roomW);
      z = rand(-roomD, roomD);
      y = -roomH * 0.45 + rand(0, 0.03);
      surface = classifyPoint(x, y, z);
    } else if (choice < 0.30) {
      // Wall points
      const wall = Math.floor(Math.random() * 4);
      if (wall === 0) { x = -roomW + rand(0, 0.08); z = rand(-roomD, roomD); }
      else if (wall === 1) { x = roomW - rand(0, 0.08); z = rand(-roomD, roomD); }
      else if (wall === 2) { x = rand(-roomW, roomW); z = -roomD + rand(0, 0.08); }
      else { x = rand(-roomW, roomW); z = roomD - rand(0, 0.08); }
      y = rand(-roomH * 0.45, roomH * 0.45);
      surface = classifyPoint(x, y, z);
    } else if (choice < 0.40) {
      // Ceiling
      x = rand(-roomW, roomW);
      z = rand(-roomD, roomD);
      y = roomH * 0.45 - rand(0, 0.03);
      surface = 'ceiling';
    } else if (choice < 0.52) {
      // Sofa volume
      const sofaX = -1.5, sofaZ = 1.0, sofaW = 1.6, sofaD = 0.8;
      x = rand(sofaX - sofaW, sofaX + sofaW);
      z = rand(sofaZ - sofaD, sofaZ + sofaD);
      // Sofa shape: seat + back
      const floorY = -roomH * 0.45;
      if (Math.random() < 0.7) {
        y = floorY + rand(0.2, 0.55); // seat
      } else {
        y = floorY + rand(0.45, 0.75); // back cushion
        z = sofaZ - sofaD + rand(0, 0.1);
      }
      surface = 'sofa';
    } else if (choice < 0.62) {
      // Coffee table
      const floorY = -roomH * 0.45;
      x = rand(-0.7, 0.7);
      z = rand(-0.3, 0.7);
      y = floorY + rand(0.3, 0.45);
      surface = 'table';
    } else if (choice < 0.70) {
      // TV / entertainment unit
      const floorY = -roomH * 0.45;
      x = rand(-0.9, 0.9);
      z = -roomD + rand(0.15, 0.45);
      y = floorY + rand(0.35, 1.3);
      surface = y > floorY + 0.9 ? 'tv' : 'wall';
    } else if (choice < 0.76) {
      // Rug
      const floorY = -roomH * 0.45;
      x = rand(-2.0, 2.0);
      z = rand(-1.5, 1.5);
      y = floorY;
      surface = 'rug';
    } else if (choice < 0.82) {
      // Plant
      const floorY = -roomH * 0.45;
      const cx = 2.2, cz = 2.2;
      const angle = Math.random() * Math.PI * 2;
      const rad = Math.random() * 0.3;
      x = cx + Math.cos(angle) * rad;
      z = cz + Math.sin(angle) * rad;
      y = floorY + rand(0, 0.9);
      surface = 'plant';
    } else if (choice < 0.87) {
      // Lamp
      const floorY = -roomH * 0.45;
      const cx = 2.0, cz = 1.5;
      const angle = Math.random() * Math.PI * 2;
      const rad = Math.random() * 0.2;
      x = cx + Math.cos(angle) * rad;
      z = cz + Math.sin(angle) * rad;
      y = floorY + rand(0, 1.5);
      surface = 'lamp';
    } else {
      // Scattered room-fill points
      x = rand(-roomW * 0.8, roomW * 0.8);
      y = rand(-roomH * 0.4, roomH * 0.4);
      z = rand(-roomD * 0.8, roomD * 0.8);
      surface = classifyPoint(x, y, z);
    }

    const col = surfaceColors[surface];

    // Add subtle color variation
    const noise = (Math.random() - 0.5) * 0.08;
    const r = clamp(col.r + noise, 0, 1);
    const g = clamp(col.g + noise, 0, 1);
    const b = clamp(col.b + noise, 0, 1);

    // Normals (approximate based on position, not critical for 3DGS)
    const nx = x > roomW - 0.3 ? -1 : x < -roomW + 0.3 ? 1 : 0;
    const ny = y > roomH * 0.4 ? -1 : y < -roomH * 0.4 + 0.1 ? 1 : 0;
    const nz = z > roomD - 0.3 ? -1 : z < -roomD + 0.3 ? 1 : 0;
    const nLen = Math.sqrt(nx * nx + ny * ny + nz * nz) || 1;
    const nnx = nx / nLen + rand(-0.15, 0.15);
    const nny = ny / nLen + rand(-0.15, 0.15);
    const nnz = nz / nLen + rand(-0.15, 0.15);

    // SH DC coefficients (raw values, no sigmoid/logit encoding)
    // Viewer applies: color = SH_C0 * f_dc + 0.5
    const sh_dc0 = colorToSH(r);
    const sh_dc1 = colorToSH(g);
    const sh_dc2 = colorToSH(b);

    // Higher-order SH = near zero (stored as raw values, will be small after sigmoid correction)
    const shRestRand = (): number => rand(-0.1, 0.1);

    // Opacity: high for surfaces
    const opacity = invSigmoid(0.85 + rand(-0.1, 0.1));

    // Scale: small gaussians for sharp surfaces (log scale, stored directly)
    const scaleBase = Math.exp(rand(-2.5, -1.8)); // 0.08 to 0.16 world units
    const scale0 = Math.log(scaleBase * rand(0.8, 1.2));
    const scale1 = Math.log(scaleBase * rand(0.8, 1.2));
    const scale2 = Math.log(scaleBase * rand(0.8, 1.2));

    // Rotation: identity quaternion with slight noise
    const qw = 1.0 + rand(-0.05, 0.05);
    const qx = rand(-0.05, 0.05);
    const qy = rand(-0.05, 0.05);
    const qz = rand(-0.05, 0.05);
    const qLen = Math.sqrt(qw * qw + qx * qx + qy * qy + qz * qz);
    const rot0 = qw / qLen;
    const rot1 = qx / qLen;
    const rot2 = qy / qLen;
    const rot3 = qz / qLen;

    const float = (v: number): void => { buf.writeFloatLE(v, offset); offset += 4; };

    float(x);
    float(y);
    float(z);
    float(nnx);
    float(nny);
    float(nnz);
    float(sh_dc0);
    float(sh_dc1);
    float(sh_dc2);
    // f_rest 0..44
    for (let j = 0; j < 45; j++) float(shRestRand());
    float(opacity);
    float(scale0);
    float(scale1);
    float(scale2);
    float(rot0);
    float(rot1);
    float(rot2);
    float(rot3);
  }

  return buf;
}

// ---------------------------------------------------------------------------
// S3 client
// ---------------------------------------------------------------------------
function buildS3Client() {
  return new S3Client({
    endpoint: process.env.S3_ENDPOINT || 'http://minio:9000',
    region: process.env.S3_REGION || 'us-east-1',
    credentials: {
      accessKeyId: process.env.S3_ACCESS_KEY || 'minioadmin',
      secretAccessKey: process.env.S3_SECRET_KEY || 'minioadmin',
    },
    forcePathStyle: process.env.S3_FORCE_PATH_STYLE !== 'false',
  });
}

async function ensureBucket(s3: S3Client, bucket: string) {
  try {
    await s3.send(new HeadBucketCommand({ Bucket: bucket }));
    console.log(`Bucket "${bucket}" exists.`);
  } catch {
    console.log(`Creating bucket "${bucket}"...`);
    await s3.send(new CreateBucketCommand({ Bucket: bucket }));
    console.log(`Bucket "${bucket}" created.`);
  }
}

async function main() {
  console.log('[seed] Starting...');

  const s3 = buildS3Client();
  const bucket = process.env.S3_BUCKET || 'gsplat-assets';

  // Ensure bucket exists
  await ensureBucket(s3, bucket);

  // ── Admin user ──
  const adminEmail = process.env.ADMIN_SEED_EMAIL || 'admin@example.com';
  const adminPassword = process.env.ADMIN_SEED_PASSWORD || 'admin12345';
  const passwordHash = await bcrypt.hash(adminPassword, 12);

  const admin = await prisma.user.upsert({
    where: { email: adminEmail },
    update: {},
    create: {
      email: adminEmail,
      passwordHash,
      role: 'ADMIN',
    },
  });
  console.log(`Admin: ${admin.email}`);

  // ── Demo splat ──
  const demoSlug = 'demo-scene';
  const demoId = '00000000-0000-4000-8000-000000000001';

  console.log('[seed] Generating Gaussian Splat PLY (this takes ~30s for 300k points)...');
  const pointCount = 300_000; // Good visual quality, ~ 15 MB PLY file
  const plyBuffer = generateGaussianSplatPLY(pointCount);
  console.log(`[seed] PLY generated: ${(plyBuffer.byteLength / 1024 / 1024).toFixed(2)} MB`);

  // Upload to MinIO
  const version = 1;
  const objKey = `splats/${demoId}/versions/${version}/scene.ply`;
  const posterKey = `splats/${demoId}/versions/${version}/poster.png`;

  console.log(`[seed] Uploading PLY to s3://${bucket}/${objKey}...`);
  await s3.send(
    new PutObjectCommand({
      Bucket: bucket,
      Key: objKey,
      Body: plyBuffer,
      ContentType: 'application/octet-stream',
      Metadata: {
        'splat-format': 'ply',
        'splat-count': String(pointCount),
      },
    }),
  );
  console.log('[seed] PLY uploaded.');

  // ── Generate simple poster (blank PNG placeholder) ──
  // We create a minimal 1x1 PNG and upload it. The viewer will show it during loading.
  const minimalPNG = Buffer.from(
    'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPj/HwADBwIAMCbHYQAAAABJRU5ErkJggg==',
    'base64',
  );
  await s3.send(
    new PutObjectCommand({
      Bucket: bucket,
      Key: posterKey,
      Body: minimalPNG,
      ContentType: 'image/png',
    }),
  );
  console.log('[seed] Poster uploaded.');

  // ── Database record ──
  const demoSplat = await prisma.splat.upsert({
    where: { slug: demoSlug },
    update: {
      productionFormat: 'ply',
      productionObjectKey: objKey,
      posterKey,
      splatCount: pointCount,
      sourceFormat: 'ply',
      sourceObjectKey: `splats/${demoId}/originals/1/source.ply`,
      status: 'PUBLISHED',
    },
    create: {
      id: demoId,
      slug: demoSlug,
      title: 'Demo Living Room',
      description: 'A demonstration Gaussian Splat scene of a modern living room. Browse the room, click markers to learn about furniture pieces. Upload your own .ply or .sog file through the admin panel.',
      status: 'PUBLISHED',
      sourceFormat: 'ply',
      productionFormat: 'ply',
      sourceObjectKey: `splats/${demoId}/originals/1/source.ply`,
      productionObjectKey: objKey,
      posterKey,
      splatCount: pointCount,
      sizeBytes: BigInt(plyBuffer.byteLength),
      publishedAt: new Date(),
      defaultCameraJson: {
        position: [0, 1.2, 3.0],
        target: [0, 0.4, 0],
      },
      boundingBoxJson: {
        min: [-4, -1.2, -3.5],
        max: [4, 1.2, 3.5],
      },
    },
  });

  console.log(`Demo splat: ${demoSplat.slug} (id=${demoSplat.id})`);

  // ── Demo annotations ──
  const demoAnnotations = [
    {
      splatId: demoSplat.id,
      title: 'Sofa',
      body: 'Modern grey sectional sofa with deep seating and chaise lounges on both sides.',
      kind: 'info',
      positionX: -1.5,
      positionY: -0.6,
      positionZ: 1.0,
      icon: 'furniture',
    },
    {
      splatId: demoSplat.id,
      title: 'TV Unit',
      body: '65-inch OLED TV mounted on a minimalist floating entertainment unit.',
      kind: 'info',
      positionX: 0,
      positionY: 0.4,
      positionZ: -3.0,
      icon: 'media',
    },
    {
      splatId: demoSplat.id,
      title: 'Coffee Table',
      body: 'Solid walnut coffee table — mid-century modern design.',
      kind: 'info',
      positionX: 0,
      positionY: -0.7,
      positionZ: 0.2,
      icon: 'furniture',
    },
    {
      splatId: demoSplat.id,
      title: 'Dining Area',
      body: 'The dining area features a 6-seat marble table with warm pendant lighting.',
      kind: 'info',
      positionX: 2.2,
      positionY: -0.5,
      positionZ: -1.5,
      icon: 'dining',
    },
    {
      splatId: demoSplat.id,
      title: 'Plant Corner',
      body: 'Large fiddle-leaf fig plant in a ceramic planter.',
      kind: 'info',
      positionX: 2.2,
      positionY: -0.2,
      positionZ: 2.2,
      icon: 'nature',
    },
    {
      splatId: demoSplat.id,
      title: 'Floor Lamp',
      body: 'Adjustable arc floor lamp with warm LED lighting.',
      kind: 'info',
      positionX: 2.0,
      positionY: 0.5,
      positionZ: 1.5,
      icon: 'lighting',
    },
  ];

  // Remove old annotations then create new
  await prisma.annotation.deleteMany({ where: { splatId: demoSplat.id } });
  for (const ann of demoAnnotations) {
    await prisma.annotation.create({ data: ann });
  }
  console.log(`Created ${demoAnnotations.length} annotations`);

  console.log('[seed] Done.');
}

main()
  .catch((e) => {
    console.error('[seed] Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
