import type { QualityProfile, QualityProfileName } from './types.js';

export const qualityProfiles: Record<QualityProfileName, QualityProfile> = {
  phoneUltraLow: {
    splatBudget: 40_000,
    maxDevicePixelRatio: 0.6,
    maxPixelDim: 720,
    enablePostFx: false,
    markerDistanceLimit: 10,
    antialias: false,
    targetFps: 30,
    adaptiveQualityEnabled: true,
    minPixelSize: 4,
    minContribution: 12,
    alphaClip: 1 / 48,
    lodBaseDistanceScale: 0.12,
    lodMultiplier: 2.25,
    lodRange: [3, 3],
    highQualitySH: false,
    renderOnDemand: true,
    preferredRenderer: 'webgl2',
  },
  phoneLow: {
    splatBudget: 75_000,
    maxDevicePixelRatio: 0.75,
    maxPixelDim: 900,
    enablePostFx: false,
    markerDistanceLimit: 20,
    antialias: false,
    targetFps: 30,
    adaptiveQualityEnabled: true,
    minPixelSize: 3.25,
    minContribution: 8,
    alphaClip: 1 / 64,
    lodBaseDistanceScale: 0.15,
    lodMultiplier: 2.5,
    lodRange: [2, 3],
    highQualitySH: false,
    renderOnDemand: true,
    preferredRenderer: 'webgl2',
  },
  phoneHigh: {
    splatBudget: 250_000,
    maxDevicePixelRatio: 1,
    maxPixelDim: 1080,
    enablePostFx: false,
    markerDistanceLimit: 30,
    antialias: false,
    targetFps: 45,
    adaptiveQualityEnabled: true,
    minPixelSize: 2,
    minContribution: 4,
    alphaClip: 1 / 255,
    lodBaseDistanceScale: 0.3,
    lodMultiplier: 3,
    lodRange: [1, 3],
    highQualitySH: false,
    renderOnDemand: true,
    preferredRenderer: 'auto',
  },
  desktopMedium: {
    splatBudget: 900_000,
    maxDevicePixelRatio: 1.5,
    maxPixelDim: 1440,
    enablePostFx: true,
    markerDistanceLimit: 60,
    antialias: false,
    targetFps: 60,
    adaptiveQualityEnabled: true,
    minPixelSize: 1.25,
    minContribution: 2,
    alphaClip: 1 / 255,
    lodBaseDistanceScale: 0.6,
    lodMultiplier: 3,
    lodRange: [0, 3],
    highQualitySH: true,
    renderOnDemand: true,
    preferredRenderer: 'webgl2',
  },
  desktopHigh: {
    splatBudget: 3_000_000,
    maxDevicePixelRatio: 2,
    maxPixelDim: 2160,
    enablePostFx: true,
    markerDistanceLimit: 100,
    antialias: true,
    targetFps: 60,
    adaptiveQualityEnabled: true,
    minPixelSize: 0.75,
    minContribution: 1,
    alphaClip: 1 / 255,
    lodBaseDistanceScale: 1,
    lodMultiplier: 3,
    lodRange: [0, 3],
    highQualitySH: true,
    renderOnDemand: true,
    preferredRenderer: 'webgl2',
  },
  vrQuest: {
    splatBudget: 60_000,
    maxDevicePixelRatio: 0.75,
    maxPixelDim: 1024,
    enablePostFx: false,
    markerDistanceLimit: 40,
    antialias: false,
    targetFps: 72,
    adaptiveQualityEnabled: true,
    minPixelSize: 5,
    minContribution: 14,
    alphaClip: 1 / 32,
    lodBaseDistanceScale: 0.15,
    lodMultiplier: 2.75,
    lodRange: [3, 3],
    highQualitySH: false,
    renderOnDemand: false,
    preferredRenderer: 'webgl2',
    xrFramebufferScale: 0.6,
    xrFixedFoveation: 1,
    radialSorting: true,
    nearClip: 0.08,
    targetActiveSplats: 60_000,
    lodUpdateAngle: 90,
  },
  vrQuestHigh: {
    splatBudget: 600_000,
    maxDevicePixelRatio: 1.25,
    maxPixelDim: 1800,
    enablePostFx: true,
    markerDistanceLimit: 60,
    antialias: true,
    targetFps: 72,
    adaptiveQualityEnabled: false,
    minPixelSize: 0.625,
    minContribution: 1,
    alphaClip: 1 / 510,
    lodBaseDistanceScale: 1.2,
    lodMultiplier: 3.25,
    lodRange: [0, 3],
    highQualitySH: true,
    renderOnDemand: false,
    preferredRenderer: 'webgl2',
    xrFramebufferScale: 0.9,
    xrFixedFoveation: 0.35,
    radialSorting: true,
    nearClip: 0.04,
    targetActiveSplats: 600_000,
    lodUpdateAngle: 15,
  },
};

export const qualityPresetLabels: Record<string, string> = {
  auto: 'Auto',
  low: 'Low',
  medium: 'Medium',
  high: 'High',
};

export const acceptedExtensions = ['.ply', '.spz', '.sog', '.meta.json', '.lod-meta.json', '.compressed.ply'];

export const defaultLodBudget = 900_000;
export const defaultMobileLodBudget = 250_000;
export const defaultVrLodBudget = 60_000;
